// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * State is the UI-facing status of the local proxy.
 */
export class State {
    /**
     * Creates a new State instance.
     * @param {Partial<State>} [$$source = {}] - The source object to create the State.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("external" in $$source)) {
            /**
             * health answered but we did not start it
             * @member
             * @type {boolean}
             */
            this["external"] = false;
        }
        if (!("baseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseUrl"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("binaryPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["binaryPath"] = "";
        }
        if (!("binaryExists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["binaryExists"] = false;
        }
        if (!("sourceRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceRoot"] = "";
        }
        if (!("sourceFound" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sourceFound"] = false;
        }
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }
        if (!("lastError" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {State}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new State(/** @type {Partial<State>} */($$parsedSource));
    }
}
