// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Phase enumerates the login state machine.
 * @readonly
 * @enum {string}
 */
export const Phase = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PhaseIdle: "idle",
    PhaseSwapping: "swapping",

    /**
     * terminal spawned; awaiting auth.json
     */
    PhaseWaiting: "waiting",
    PhaseFinishing: "finishing",

    /**
     * new/known account handled, original restored
     */
    PhaseDone: "done",

    /**
     * aborted/failed; original restored
     */
    PhaseRestored: "restored",
    PhaseError: "error",
};

/**
 * Status is the UI-facing progress snapshot, emitted as an app event and
 * returned from State().
 */
export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("phase" in $$source)) {
            /**
             * @member
             * @type {Phase}
             */
            this["phase"] = Phase.$zero;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}
