import { Events } from "@wailsio/runtime";
import * as App from "../bindings/commandcode-desktop/app.js";

// Typed bindings generated by `wails3 generate bindings`.
const svc = () => App;

let snapshot = null;
const busy = new Set(); // element ids currently running an action

const $ = (id) => document.getElementById(id);

function esc(s) {
  return String(s ?? "").replace(/[&<>"']/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
}

function fmtTime(iso) {
  if (!iso) return "—";
  const d = new Date(iso);
  return isNaN(d) ? iso : d.toLocaleString("zh-CN", { hour12: false });
}

let toastTimer;
function toast(msg, isErr = false) {
  const t = $("toast");
  t.textContent = msg;
  t.className = isErr ? "err" : "";
  t.style.display = "block";
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => (t.style.display = "none"), 5000);
}

async function call(name, fn) {
  if (busy.has(name)) return;
  busy.add(name);
  try {
    await fn();
  } catch (e) {
    toast(String(e?.message ?? e), true);
  } finally {
    busy.delete(name);
  }
}

// ---------------------------------------------------------------- rendering

function renderProxy() {
  const p = snapshot.proxy;
  const dot = $("proxyDot"), txt = $("proxyText");
  if (p.running && !p.external) {
    dot.className = "dot ok";
    txt.textContent = `运行中 · v${p.version || "?"} · ${p.baseUrl} · pid ${p.pid}`;
  } else if (p.running && p.external) {
    dot.className = "dot ext";
    txt.textContent = `已在运行（外部实例，非本程序启动）· ${p.baseUrl}`;
  } else {
    dot.className = "dot off";
    txt.textContent = `未运行 · ${p.baseUrl}`;
  }
  $("btnProxyStart").disabled = p.running;
  $("btnProxyStop").disabled = !p.running || p.external;
  $("btnDashboard").disabled = !p.running;
  $("proxyBinaryHint").textContent =
    p.binaryPath ? `二进制：${p.binaryPath}` :
    p.sourceFound ? `尚未构建 — 将从源码仓库构建：${p.sourceRoot}` :
    "尚未构建，且未找到源码仓库（可在设置里指定路径）";
  $("proxyBase").textContent = p.baseUrl || "";
}

function planCell(a) {
  if (!a.plan) return `<span class="plan-none">未探测</span>`;
  const when = new Date(a.plan.probeAt).toLocaleString("zh-CN", { hour12: false });
  if (a.plan.blocked) {
    return `<span class="plan-no" title="${esc(a.plan.reason || "")}">⛔ ${esc(a.plan.reason || "账户无额度")}</span>
            <span class="plan-none">· ${esc(when)}</span>`;
  }
  const ok = (a.plan.allowed || []).length;
  const no = (a.plan.denied || []).length;
  const reason = a.plan.reason ? ` <span class="plan-none" title="${esc(a.plan.reason)}">(${esc(a.plan.reason)})</span>` : "";
  return `<span class="plan-ok">✓${ok}</span> / <span class="plan-no">✗${no}</span>${reason}
          <span class="plan-none">· ${esc(when)}</span>`;
}

function renderAccounts() {
  const body = $("acctBody");
  const list = snapshot.accounts || [];
  if (!list.length) {
    body.innerHTML = `<tr><td colspan="5" class="plan-none">保管库为空 — 点「登录新账号」或「导入当前 CLI 已登录账号」。</td></tr>`;
  } else {
    body.innerHTML = list.map((a) => `
      <tr>
        <td>${esc(a.userName || a.userId)} ${a.active ? `<span class="badge active">当前</span>` : ""}</td>
        <td><span id="note-${esc(a.id)}">${a.note ? esc(a.note) : '<span class="plan-none">—</span>'}</span>
            <button data-act="note" data-id="${esc(a.id)}" title="编辑备注" style="padding:2px 7px">✎</button></td>
        <td class="mono">${esc(a.maskedKey)}</td>
        <td>${planCell(a)}</td>
        <td class="mono">${esc(fmtTime(a.authenticatedAt))}</td>
        <td style="text-align:right">
          ${a.active ? "" : `<button data-act="activate" data-id="${esc(a.id)}">切换</button>`}
          <button data-act="plan" data-id="${esc(a.id)}">查套餐</button>
          <button data-act="remove" data-id="${esc(a.id)}" class="danger">删除</button>
        </td>
      </tr>`).join("");
    body.querySelectorAll("button[data-act]").forEach((btn) => {
      btn.addEventListener("click", () => onAccountAction(btn.dataset.act, btn.dataset.id, btn));
    });
    $("closeAction").value = snapshot.closeAction || "tray";
  }
  const dir = snapshot.dirUser
    ? `CLI 目录当前账号：<b>${esc(snapshot.dirUserName || snapshot.dirUser)}</b>（${esc(snapshot.dirKeyHint)}）`
    : "CLI 目录当前没有账号（~/.commandcode/auth.json 不存在）。";
  $("dirHint").innerHTML = dir +
    (!ACTIVE_PHASES.includes((snapshot.login || {}).phase) && snapshot.activeId && snapshot.activeId !== snapshot.dirUser
      ? ` <span class="plan-no">⚠ 与保管库记录的“当前”（${esc(snapshot.activeId)}）不一致，建议先点「切换」对齐。</span>` : "");
}

const ACTIVE_PHASES = ["swapping", "waiting", "finishing"];
let loginFinal = null; // 保留 done/restored/error 的结果信息直到用户关闭或再次登录

function renderLogin() {
  const l = snapshot.login || { phase: "idle" };
  const active = ACTIVE_PHASES.includes(l.phase);
  if (active) loginFinal = null;
  const box = $("loginBox");
  const msg = active ? l : (loginFinal || l);
  const show = active || !!loginFinal || ["done", "restored", "error"].includes(l.phase);
  box.style.display = show ? "block" : "none";
  $("loginMsg").textContent = msg.message || "";
  $("btnLoginAbort").style.display = active ? "" : "none";
  $("btnLoginClose").style.display = active ? "none" : "";
  $("btnLogin").disabled = active;
}

function renderHelper() {
  $("keyHelperPath").textContent = snapshot.keyHelper || "（无法创建 keyhelper 脚本）";
}

// ---------------------------------------------------------------- actions

async function refresh() {
  try {
    snapshot = await svc().Snapshot();
    renderProxy(); renderAccounts(); renderLogin(); renderHelper();
  } catch (e) {
    if (!snapshot) toast(`初始化失败：${e?.message ?? e}`, true);
  }
}

async function onAccountAction(act, id, btn) {
  await call(act + id, async () => {
    btn.disabled = true;
    try {
      if (act === "activate") {
        await svc().Activate(id);
        toast("已切换账号，Claude Code 等消费端将自动使用新密钥");
      } else if (act === "note") {
        const cur = snapshot.accounts.find((x) => x.id === id)?.note || "";
        const v = prompt("备注（如套餐、手机号、用途等）：", cur);
        if (v === null) return;
        await svc().SetNote(id, v.trim());
        toast("备注已保存");
      } else if (act === "remove") {
        if (!confirm("从保管库删除这个账号？（不会动 ~/.commandcode 里的当前账号）")) return;
        await svc().Remove(id);
      } else if (act === "plan") {
        btn.textContent = "探测中…";
        await svc().RefreshPlan(id);
        toast("套餐探测完成");
      }
    } finally {
      btn.disabled = false;
      if (act === "plan") btn.textContent = "查套餐";
      await refresh();
    }
  });
}

$("btnLogin").addEventListener("click", () => call("login", async () => {
  await svc().StartLogin();
  await refresh();
}));
$("btnLoginAbort").addEventListener("click", () => call("abort", async () => {
  await svc().AbortLogin();
}));
$("btnLoginClose").addEventListener("click", () => {
  loginFinal = null;
  if (snapshot) { snapshot.login = { phase: "idle", message: "" }; }
  renderLogin();
});
$("btnImport").addEventListener("click", () => call("import", async () => {
  await svc().ImportCurrent();
  toast("已导入保管库");
  await refresh();
}));
$("btnRefresh").addEventListener("click", () => call("refresh", refresh));
$("btnProxyStart").addEventListener("click", () => call("pxStart", async () => {
  await svc().StartProxy();
  await refresh();
}));
$("btnProxyStop").addEventListener("click", () => call("pxStop", async () => {
  await svc().StopProxy();
  await refresh();
}));
$("btnProxyBuild").addEventListener("click", () => call("pxBuild", async () => {
  toast("正在构建 commandcode-proxy…");
  await svc().BuildProxy();
  toast("构建完成");
  await refresh();
}));
$("btnDashboard").addEventListener("click", () => call("dash", async () => {
  await svc().OpenDashboard();
}));
$("closeAction").addEventListener("change", (e) => call("closeAction", async () => {
  await svc().SetCloseAction(e.target.value);
  toast(e.target.value === "tray" ? "关闭窗口将最小化到托盘" : "关闭窗口将退出程序");
}));
$("btnCopyHelper").addEventListener("click", () => call("copy", async () => {
  await navigator.clipboard.writeText(snapshot.keyHelper || "");
  toast("已复制 keyhelper 路径");
}));

// Events from Go.
Events.On("login:status", (ev) => {
  if (snapshot) snapshot.login = ev.data;
  if (["done", "restored", "error"].includes(ev.data.phase)) loginFinal = ev.data;
  renderLogin();
  if (["done", "restored", "error"].includes(ev.data.phase)) refresh();
});
Events.On("app:changed", () => refresh());
Events.On("app:error", (ev) => toast(String(ev.data ?? ev), true));

refresh();
setInterval(() => { if (!busy.size) refresh(); }, 15000);
