// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PlanInfo caches the per-account plan probe (which models its key can use).
 */
export class PlanInfo {
    /**
     * Creates a new PlanInfo instance.
     * @param {Partial<PlanInfo>} [$$source = {}] - The source object to create the PlanInfo.
     */
    constructor($$source = {}) {
        if (!("probeAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["probeAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("allowed" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["allowed"] = [];
        }
        if (!("denied" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["denied"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["quotaHeaders"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Blocked = the account cannot make any request (no credits/purchased plan).
             * @member
             * @type {boolean | undefined}
             */
            this["blocked"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reason"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlanInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlanInfo}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $Create.DateFromTime;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("probeAt" in $$parsedSource) {
            $$parsedSource["probeAt"] = $$createField0_0($$parsedSource["probeAt"]);
        }
        if ("allowed" in $$parsedSource) {
            $$parsedSource["allowed"] = $$createField1_0($$parsedSource["allowed"]);
        }
        if ("denied" in $$parsedSource) {
            $$parsedSource["denied"] = $$createField2_0($$parsedSource["denied"]);
        }
        if ("quotaHeaders" in $$parsedSource) {
            $$parsedSource["quotaHeaders"] = $$createField3_0($$parsedSource["quotaHeaders"]);
        }
        return new PlanInfo(/** @type {Partial<PlanInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
