// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Config is persisted to config.json. Zero fields fall back to defaults.
 */
export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("proxyHost" in $$source)) {
            /**
             * ProxyHost/ProxyPort describe where the local proxy listens (also the
             * probe endpoint).
             * @member
             * @type {string}
             */
            this["proxyHost"] = "";
        }
        if (!("proxyPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["proxyPort"] = 0;
        }
        if (!("proxyBinary" in $$source)) {
            /**
             * ProxyBinary is an absolute path to a commandcode-proxy executable. When
             * empty the app manages its own copy under the app-data dir and builds it
             * from ProxySource when needed.
             * @member
             * @type {string}
             */
            this["proxyBinary"] = "";
        }
        if (!("proxySource" in $$source)) {
            /**
             * ProxySource is the commandcode-proxy-go repository root, used to build
             * ProxyBinary with `go build ./cmd/commandcode-proxy`.
             * @member
             * @type {string}
             */
            this["proxySource"] = "";
        }
        if (!("vaultRoot" in $$source)) {
            /**
             * VaultRoot overrides the credential archive location.
             * @member
             * @type {string}
             */
            this["vaultRoot"] = "";
        }
        if (!("modelsURL" in $$source)) {
            /**
             * ModelsURL is Command Code's global model catalog endpoint.
             * @member
             * @type {string}
             */
            this["modelsURL"] = "";
        }
        if (!("probeModels" in $$source)) {
            /**
             * ProbeModels are model ids exercised against the account key to infer
             * plan availability.
             * @member
             * @type {string[]}
             */
            this["probeModels"] = [];
        }
        if (!("cliCommand" in $$source)) {
            /**
             * CLICommand overrides the login executable name.
             * @member
             * @type {string}
             */
            this["cliCommand"] = "";
        }
        if (!("closeAction" in $$source)) {
            /**
             * CloseAction: what clicking the window X does — "tray" hides to the
             * system tray (default), "quit" exits the app.
             * @member
             * @type {string}
             */
            this["closeAction"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("probeModels" in $$parsedSource) {
            $$parsedSource["probeModels"] = $$createField6_0($$parsedSource["probeModels"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
