// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CatalogEntry is one model in Command Code's global catalog.
 */
export class CatalogEntry {
    /**
     * Creates a new CatalogEntry instance.
     * @param {Partial<CatalogEntry>} [$$source = {}] - The source object to create the CatalogEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("context_length" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["context_length"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CatalogEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CatalogEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CatalogEntry(/** @type {Partial<CatalogEntry>} */($$parsedSource));
    }
}
