// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App holds long-lived managers. It is constructed once in main.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as probe$0 from "./internal/probe/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as proxy$0 from "./internal/proxy/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "./internal/settings/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AbortLogin cancels an in-progress login.
 * @returns {$CancellablePromise<void>}
 */
export function AbortLogin() {
    return $Call.ByID(1742717366);
}

/**
 * Activate makes a vault account the current one everywhere: it installs the
 * auth.json into the CLI directory, records the marker, and exports the key
 * for apiKeyHelper consumers.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Activate(id) {
    return $Call.ByID(745053992, id);
}

/**
 * ActiveAccountID returns the last activated account id.
 * @returns {$CancellablePromise<string>}
 */
export function ActiveAccountID() {
    return $Call.ByID(3369135023);
}

/**
 * BuildProxy recompiles the proxy from the repository.
 * @returns {$CancellablePromise<void>}
 */
export function BuildProxy() {
    return $Call.ByID(3487576021);
}

/**
 * Catalog returns Command Code's global model list (cached per process).
 * @returns {$CancellablePromise<probe$0.CatalogEntry[]>}
 */
export function Catalog() {
    return $Call.ByID(4127120016).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CloseActionIsTray reports the configured window-X behavior.
 * @returns {$CancellablePromise<boolean>}
 */
export function CloseActionIsTray() {
    return $Call.ByID(2711328281);
}

/**
 * Deactivate removes the active credential (auth.json + exported key).
 * @returns {$CancellablePromise<void>}
 */
export function Deactivate() {
    return $Call.ByID(1985004331);
}

/**
 * EmitError pushes a toast message to the frontend.
 * @param {string} msg
 * @returns {$CancellablePromise<void>}
 */
export function EmitError(msg) {
    return $Call.ByID(552483796, msg);
}

/**
 * ImportCurrent archives the account currently logged in via the CLI.
 * @returns {$CancellablePromise<void>}
 */
export function ImportCurrent() {
    return $Call.ByID(2336012425);
}

/**
 * MainWindow exposes the primary window for tray wiring.
 * @returns {$CancellablePromise<application$0.Window>}
 */
export function MainWindow() {
    return $Call.ByID(1786880252);
}

/**
 * OpenDashboard opens the proxy's /admin page in the system browser.
 * @returns {$CancellablePromise<void>}
 */
export function OpenDashboard() {
    return $Call.ByID(2520657463);
}

/**
 * ProxyRunning reports tray menu state.
 * @returns {$CancellablePromise<boolean>}
 */
export function ProxyRunning() {
    return $Call.ByID(134038994);
}

/**
 * ProxyStatus returns the child-process state.
 * @returns {$CancellablePromise<proxy$0.State>}
 */
export function ProxyStatus() {
    return $Call.ByID(3054196149).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * RefreshPlan probes a vault account's key against the configured models and
 * caches the result. The local proxy must be running (it is the known-good
 * translation layer).
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RefreshPlan(id) {
    return $Call.ByID(1384970703, id);
}

/**
 * Remove deletes an account from the vault (never the active auth.json file).
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Remove(id) {
    return $Call.ByID(1395520005, id);
}

/**
 * SaveConfig updates host/port/probe settings and rebuilds the proxy manager.
 * @param {settings$0.Config} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(cfg) {
    return $Call.ByID(3442292638, cfg);
}

/**
 * SetAccountsChangedHook lets main.go refresh the tray menu on any change.
 * @param {any} fn
 * @returns {$CancellablePromise<void>}
 */
export function SetAccountsChangedHook(fn) {
    return $Call.ByID(2453251210, fn);
}

/**
 * SetCloseAction configures whether the window X hides to tray or quits.
 * @param {string} action
 * @returns {$CancellablePromise<void>}
 */
export function SetCloseAction(action) {
    return $Call.ByID(4173316595, action);
}

/**
 * SetMainWindow stores the window created in main.go.
 * @param {application$0.Window} w
 * @returns {$CancellablePromise<void>}
 */
export function SetMainWindow(w) {
    return $Call.ByID(843697430, w);
}

/**
 * SetNote updates an account's free-form remark.
 * @param {string} id
 * @param {string} note
 * @returns {$CancellablePromise<void>}
 */
export function SetNote(id, note) {
    return $Call.ByID(408035451, id, note);
}

/**
 * SetRuntime stores the Wails app for event emission.
 * @param {application$0.App | null} r
 * @returns {$CancellablePromise<void>}
 */
export function SetRuntime(r) {
    return $Call.ByID(594833949, r);
}

/**
 * ShowWindow brings the main window back from the tray.
 * @returns {$CancellablePromise<void>}
 */
export function ShowWindow() {
    return $Call.ByID(31117496);
}

/**
 * Snapshot returns the full UI state.
 * @returns {$CancellablePromise<$models.Snapshot | null>}
 */
export function Snapshot() {
    return $Call.ByID(365975013).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * StartLogin begins the browser sign-in flow for a NEW account. The active
 * account is preserved.
 * @returns {$CancellablePromise<void>}
 */
export function StartLogin() {
    return $Call.ByID(1421317340);
}

/**
 * StartProxy ensures the binary exists (building if needed) and runs it.
 * @returns {$CancellablePromise<void>}
 */
export function StartProxy() {
    return $Call.ByID(2835838209);
}

/**
 * StopProxy terminates the managed child process.
 * @returns {$CancellablePromise<void>}
 */
export function StopProxy() {
    return $Call.ByID(3345047379);
}

// Private type creation functions
const $$createType0 = probe$0.CatalogEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = proxy$0.State.createFrom;
const $$createType3 = $models.Snapshot.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
