// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as login$0 from "./internal/login/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as proxy$0 from "./internal/proxy/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vault$0 from "./internal/vault/models.js";

/**
 * AccountView is one vault account plus its activation state.
 */
export class AccountView {
    /**
     * Creates a new AccountView instance.
     * @param {Partial<AccountView>} [$$source = {}] - The source object to create the AccountView.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * sanitized userId (directory name)
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("userId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["userId"] = "";
        }
        if (!("userName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["userName"] = "";
        }
        if (!("keyName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["keyName"] = "";
        }
        if (!("authenticatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["authenticatedAt"] = "";
        }
        if (!("addedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["addedAt"] = "";
        }
        if (!("maskedKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["maskedKey"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["note"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {vault$0.PlanInfo | null | undefined}
             */
            this["plan"] = undefined;
        }
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccountView}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("plan" in $$parsedSource) {
            $$parsedSource["plan"] = $$createField8_0($$parsedSource["plan"]);
        }
        return new AccountView(/** @type {Partial<AccountView>} */($$parsedSource));
    }
}

/**
 * Snapshot is everything the UI needs in one refresh.
 */
export class Snapshot {
    /**
     * Creates a new Snapshot instance.
     * @param {Partial<Snapshot>} [$$source = {}] - The source object to create the Snapshot.
     */
    constructor($$source = {}) {
        if (!("accounts" in $$source)) {
            /**
             * @member
             * @type {AccountView[]}
             */
            this["accounts"] = [];
        }
        if (!("activeId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["activeId"] = "";
        }
        if (!("dirUser" in $$source)) {
            /**
             * userId currently in ~/.commandcode ("" = none)
             * @member
             * @type {string}
             */
            this["dirUser"] = "";
        }
        if (!("dirUserName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dirUserName"] = "";
        }
        if (!("dirKeyHint" in $$source)) {
            /**
             * masked key of the dir account, if known
             * @member
             * @type {string}
             */
            this["dirKeyHint"] = "";
        }
        if (!("proxy" in $$source)) {
            /**
             * @member
             * @type {proxy$0.State}
             */
            this["proxy"] = (new proxy$0.State());
        }
        if (!("login" in $$source)) {
            /**
             * @member
             * @type {login$0.Status}
             */
            this["login"] = (new login$0.Status());
        }
        if (!("probeModels" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["probeModels"] = [];
        }
        if (!("keyHelper" in $$source)) {
            /**
             * path to the apiKeyHelper script
             * @member
             * @type {string}
             */
            this["keyHelper"] = "";
        }
        if (!("closeAction" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["closeAction"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Snapshot}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        const $$createField5_0 = $$createType4;
        const $$createField6_0 = $$createType5;
        const $$createField7_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("accounts" in $$parsedSource) {
            $$parsedSource["accounts"] = $$createField0_0($$parsedSource["accounts"]);
        }
        if ("proxy" in $$parsedSource) {
            $$parsedSource["proxy"] = $$createField5_0($$parsedSource["proxy"]);
        }
        if ("login" in $$parsedSource) {
            $$parsedSource["login"] = $$createField6_0($$parsedSource["login"]);
        }
        if ("probeModels" in $$parsedSource) {
            $$parsedSource["probeModels"] = $$createField7_0($$parsedSource["probeModels"]);
        }
        return new Snapshot(/** @type {Partial<Snapshot>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = vault$0.PlanInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = AccountView.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = proxy$0.State.createFrom;
const $$createType5 = login$0.Status.createFrom;
const $$createType6 = $Create.Array($Create.Any);
